# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45c86c3972b4b8f8dd1c66b2386808b7134c8c1eb9c53436f96b8e2a9da659bbf64736e13b285b06509c835cdaabd607b537bd6bbb95ee36898efb8f9126c217

test:
  secret_key_base: 9d38e56ad6ff588d30100a4caf35a335d237921e7dc9de6d5439c842f49e323be203071f54f34cef060e716210fedd4f9723a3fda4de087c597d42c12947dd4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
